### PR TITLE
Cylindrical and spherical versions of SurfaceFlux

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This PR implements the SurfaceFlux in cylindrical and spherical coordinates: `SurfaceFluxCylindrical` and `SurfaceFluxSpherical` as well as a little bit of refactoring.

Usage:

```python
full_coverage_cylindrical_surface_flux = F.SurfaceFluxCylindrical(field="solute", surface=1)
half_coverage_cylindrical_surface_flux = F.SurfaceFluxCylindrical(field="solute", surface=1, azimuthal_range=(0, np,pi))
```

Similarly for spherical meshes:
```python
full_coverage_spherical_surface_flux = F.SurfaceFluxSpherical(field="solute", surface=1)
quarter_coverage_spherical_surface_flux = F.SurfaceFluxSpherical(field="solute", surface=1, azimuthal_range=(0, np,pi), polar_range=(0, np.pi))
```

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [x] Black formatted
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@jhdark let me know what you think and I'll complete with documentation

**Review by jhdark — CHANGES_REQUESTED** [review]
This looks great to me, also like the fact that the units of the results are given in the doc strings, think this is smth we could implement in other export classes (accounting for differences in different dimensions).

However, just some small coverage tests that need to be added.

Then its good to go!

**Comment by RemDelaporteMathurin** [comment]
> the units of the results are given in the doc strings, think this is smth we could implement in other export classes (accounting for differences in different dimensions)

Maybe what we should do is add the units in the docstrings and also in the title of the csv column based on the dimension of the mesh

**Comment by jhdark** [comment]
I like the idea, although this could be a big change, we can add in another PR. I can make a new issue

**Review by jhdark — APPROVED** [review]
LGTM

**Pull request merged**
