### PR TITLE
Cards on front page of docs

### LINKED ISSUE #850: Documentation: add link to V&V book
It'd be nice to add the link to impressive FESTIM V&V book on the main page.

The link: https://github.com/festim-dev/V-V-report

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

Attempt at improving the front page of the documentation.

I have added clickable cards that look like this:

image

@KulaginVladimir @jhdark feel free to comment

Should fix #850 

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

### CODE REVIEW

**Comment by KulaginVladimir** [comment]
is it possible to shift icon+text blocks to the center (along the vertical)?

**Comment by RemDelaporteMathurin** [comment]
> is it possible to shift icon+text blocks to the center (along the vertical)?

Are they not already centered?

image

**Comment by KulaginVladimir** [comment]
image

**Comment by KulaginVladimir** [comment]
If it's complicated, then doesn't matter)

**Comment by RemDelaporteMathurin** [comment]
@shimwell the latest commit ensures there are three columns for all screen sizes. Would you prefer it that way or a single column for small screens?

**Pull request merged**
