### PR TITLE
added WSL and Anaconda instructions

### PR DESCRIPTION
**Pull request by rekomodo**
## Proposed changes

Add instructions to install WSL on windows and install Anaconda on WSL/Linux #866 .

## Types of changes

What types of changes does your code introduce to FESTIM?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Black formatted
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Testing on a fresh WSL default image is pending.

### CODE REVIEW

**Comment by rekomodo** [comment]
Double-checked that the commands worked on a default (Ubuntu) WSL install.

**Review by RemDelaporteMathurin — COMMENTED** [review]
Thanks @rekomodo I think this will greatly help! One day we will try to couple this with an installation video.

Could you try to also tackle #837 while we're there? I think it would just be adding a sentence or two at the very top (before installing Fenics) saying that we need to first install FEniCS the main dependency and then install FESTIM.

**Comment by rekomodo** [comment]
Latest commit implements what I got from #837 .

**Review by RemDelaporteMathurin — APPROVED** [review]
Thanks @rekomodo !

**Pull request merged**
